### ISSUE TITLE
with "docker run..." as cmd, ctrl-c leaves container running

### ISSUE THREAD

**Issue by rgarcia** [Clever/aviator#33]
aviator config:

```
gearman:
  setups:
    default:
      cmd: "docker run -i --rm --sig-proxy -p 4730:4730 rgarcia/gearmand"
      publish:
        host: localhost
        port: 4730
  requires: {}
```

If you run `aviator gearman` and hit ctrl-c, aviator exits immediately, but the container remains running.
